### ISSUE TITLE
LDAP integrace - autentizace

### ISSUE THREAD

**Issue by koubas** [HKFree/gitlab#11]
- povolit asi pro všechny členy
- nick (místo UID, jako na sojce) jako username, tohle je must have, otázka, jestli na to máme vhodný unikátní field v ldapu, který navic vyhovuje gitlabím validacím, nebo jestli GL umožní svázání podle exterího ID a všechny ostatní věci půjdou vyplnit v GL.
- nepomůže Gitlab EE? Možná na něj budeme mít jako nonprofitka nárok
Osobně mám s LDAPem pramalé zkušenosti, v gitlabu vůbec

**Comment by Kendak** [comment]
LDAP by prezdivky umel, dalo by se to nacerpat z userdb, problem je ten, ze prezdivky maji jen spravci, bezni useri, tak jak mas v prvni odrazce nemaji prezdivky.  
  
Takze to bude fungovat v podstate jen pro spravce.  
  
UID jakozto ciselny identifikator ma uplne kazdy a je unikatni, proto se pouziva ten.   
To ze neco funguje na sojce je jen v podstate potvrzenim toho co jsem napsal v prvnim odstavci, sojku pouziva jen par lidi a to jen so.

**Comment by xjrk58** [comment]
Mozna bych se vyhnul tahani prezdivek odjinud a spis nechal kazdemu dat moznost volby. Pokud uz LDAP k necemu, tak spis na tahani skupin. Uplne nejlepsi by bylo nepripojovat to pres LDAP, ale pouzit jen SSO pro autentizaci.

**Comment by Kendak** [comment]
Ano, mame SSO, proc bychom se meli vracet ke "starsimu" zpusobu authentizace, kdyz to je uz davno vyreseno pres SSO, a pokud tam bude nejaka aplikacni vrstva, tak ta nemusi vubec resit kod authetizace, jen si poresi authorizaci.

**Comment by koubas** [comment]
SSO by bylo úplně ideální, jestli to jde rozumně spojit. Grupy z LDAPu asi nepotřebujeme, ne?

**Comment by koubas** [comment]
Nativně umí SAML jen Gitlab EE Cloud :/ Bohužel SAMLu vůbec nerozumím, ale mělo by to teda jít nějak řešit na proxy úrovni, akorát gitlab si musí umět na základě něčeho (extra halviček z proxy?) rozhodnout, jestli založit novýho usera, nebo ho přihlásit? Dokážete to někdo trochu rozepsat do novýho ticketu?

**Comment by koubas** [comment]
A teď vlastně ani nevím, co používáme, ale: https://docs.gitlab.com/ee/integration/shibboleth.html

**Comment by bkralik** [comment]
Aktuální konfig LDAPu na gitlab-sojka
gitlab.rb
```
gitlab_rails['ldap_enabled'] = true
gitlab_rails['ldap_servers'] = YAML.load_file('/etc/gitlab/ldap_settings.yml')
```

ldap_settings.yml
```
main:
  label: 'LDAP'
  host: 'ldap.hkfree.org'
  port: 636
  uid: 'uid'
  encryption: 'simple_tls'
  allow_username_or_email_login: true
  base: 'ou=people,dc=hkfree,dc=org'
```

**Comment by bkralik** [comment]
K tomu by to chtělo z LDAPu dodělat import skupin, aby to bylo secure-enough. To netuším jak se bohužel dělá, asi by se chtělo poptat hkfree-ldap-mága, tzn kendyho...

**Comment by koubas** [comment]
> K tomu by to chtělo z LDAPu dodělat import skupin

Pokud tim jsou mysleny stavajici skupiny typu SO/VV, atd, tak vidim problem v tom, ze to neni zaroven atribut, podle ktereho bys chtel strukturovat repozitare v Gitlabu, GL skupiny chces spis podle teamu, projektu o vice repech, a pod. a podle LDAP membershipu do nich zarazovat lidi. Myslim si, ze v tomhle by mohl pomoct @xjrk58 zminovany Terraform, ktery ma providera, co umi konfigurovat skupiny v gitlabu a verim (nevim), ze i providera pro sani dat z ldapu. Pak to staci dat do scheduled pipeliny.

**Comment by koubas** [comment]
... v podstate chces mapovat LDAP grupy na gitlab role. Kdyby je Gitlab mel :)

**Comment by koubas** [comment]
dale v #16
